### ISSUE TITLE
Weights not available

### ISSUE THREAD

**Issue by gopikm** [yuyu2172/share-weights#1]
The default weights for chainer RCNN were from your github repo, since you have taken it down the default option isn't working. Could you kindly put up the weights again?

**Comment by yuyu2172** [comment]
Which one are talking about?
Could you tell me the url from which you are trying to download?

**Comment by gopikm** [comment]
https://github.com/yuyu2172/share-weights/releases/download/0.0.3/faster_rcnn_vgg16_voc07_2017_06_06.npz

**Comment by yuyu2172** [comment]
Hmm. I have no problem downloading the file in my environment.
I used `wget`.

**Comment by gopikm** [comment]
I'm getting an 'Unable to establish SSL connection' error while using wget. 
The chainercv demo script downloads the weights from that url by default, I'm getting a URLError for that.(urlopen error EOF occurred in violation of protocol)

**Comment by yuyu2172** [comment]
Hmm. I wonder if you are having a problem downloading from a file from github in general.

**Comment by gopikm** [comment]
My internet connection seems to be the issue, it isn't allowing downloads. Anyway I've switched to mobile data and it works perfectly. Thanks a lot. 
Btw, What is the size of the file?(just wanted to know because I'm using mobile data)

**Comment by yuyu2172** [comment]
486MB
It is quite huge. Sorry about that.

**Comment by yuyu2172** [comment]
If you have any other questions, please reopen this issue.
Thanks for asking!
